// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yemek_Tarifi_Site.Models;

#nullable disable

namespace Yemek_Tarifi_Site.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20250520194539_RecipeNew1")]
    partial class RecipeNew1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Yemek_Tarifi_Site.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RecipeExp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecipeHowPerson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecipeMaterial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecipePrepTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RecipeId");

                    b.ToTable("RecipeList");
                });
#pragma warning restore 612, 618
        }
    }
}
